<?php

declare(strict_types = 1);

namespace Rentpost\ForteApi\Attribute\Id;

/**
 * A single use token generated by Forte.js
 */
class OneTimeToken extends AbstractId
{
    protected function getIdPrefix(): string
    {
        return 'ott';
    }

}
